/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HabitColourEnum } from '../models/habit-colour-enum';
export interface AddHabitCommand {
  colour: HabitColourEnum;
  icon: string;
  name: string;
  positive: boolean;
}
