/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DailyHabitsDataDto } from '../models/daily-habits-data-dto';
export interface GetHabitsDataQueryResponse {
  active: boolean;
  dailyDatas: Array<DailyHabitsDataDto>;
  description: string;
  icon: string;
  id: string;
  name: string;
  positive: boolean;
}
