/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GetHabitsListQueryResponse {
  active: boolean;
  createdAt: string;
  description: string;
  name: string;
  positive: boolean;
}
