/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type HabitColourEnum = 'Green' | 'Lime' | 'Red' | 'Maroon' | 'Blue' | 'Navy' | 'Cyan' | 'Teal' | 'Pink' | 'Purple' | 'Orange' | 'Brown' | 'Yellow' | 'Olive' | 'Grey' | 'Black';
