/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DailyHabitsDataDto } from '../models/daily-habits-data-dto';
import { HabitColourEnum } from '../models/habit-colour-enum';
export interface HabitDto {
  active: boolean;
  colour: HabitColourEnum;
  dailyDatas: Array<DailyHabitsDataDto>;
  description: string;
  icon: string;
  id: string;
  lastCheckedDate: string | null;
  name: string;
  positive: boolean;
  streak: number;
}
