/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCoreHabitDataAddHabitDataPost } from '../fn/habit-data/api-core-habit-data-add-habit-data-post';
import { ApiCoreHabitDataAddHabitDataPost$Params } from '../fn/habit-data/api-core-habit-data-add-habit-data-post';
import { apiCoreHabitDataClearHabitDataPost } from '../fn/habit-data/api-core-habit-data-clear-habit-data-post';
import { ApiCoreHabitDataClearHabitDataPost$Params } from '../fn/habit-data/api-core-habit-data-clear-habit-data-post';
import { apiCoreHabitDataGetHabitsDataGet$Json } from '../fn/habit-data/api-core-habit-data-get-habits-data-get-json';
import { ApiCoreHabitDataGetHabitsDataGet$Json$Params } from '../fn/habit-data/api-core-habit-data-get-habits-data-get-json';
import { apiCoreHabitDataGetHabitsDataGet$Plain } from '../fn/habit-data/api-core-habit-data-get-habits-data-get-plain';
import { ApiCoreHabitDataGetHabitsDataGet$Plain$Params } from '../fn/habit-data/api-core-habit-data-get-habits-data-get-plain';
import { GetHabitsDataQueryResponse } from '../models/get-habits-data-query-response';

@Injectable({ providedIn: 'root' })
export class HabitDataService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCoreHabitDataAddHabitDataPost()` */
  static readonly ApiCoreHabitDataAddHabitDataPostPath = '/api/core/HabitData/add-habit-data';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitDataAddHabitDataPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitDataAddHabitDataPost$Response(params: ApiCoreHabitDataAddHabitDataPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCoreHabitDataAddHabitDataPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitDataAddHabitDataPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitDataAddHabitDataPost(params: ApiCoreHabitDataAddHabitDataPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCoreHabitDataAddHabitDataPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCoreHabitDataClearHabitDataPost()` */
  static readonly ApiCoreHabitDataClearHabitDataPostPath = '/api/core/HabitData/clear-habit-data';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitDataClearHabitDataPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitDataClearHabitDataPost$Response(params: ApiCoreHabitDataClearHabitDataPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCoreHabitDataClearHabitDataPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitDataClearHabitDataPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitDataClearHabitDataPost(params: ApiCoreHabitDataClearHabitDataPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCoreHabitDataClearHabitDataPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCoreHabitDataGetHabitsDataGet()` */
  static readonly ApiCoreHabitDataGetHabitsDataGetPath = '/api/core/HabitData/get-habits-data';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitDataGetHabitsDataGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitDataGetHabitsDataGet$Plain$Response(params?: ApiCoreHabitDataGetHabitsDataGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetHabitsDataQueryResponse>>> {
    return apiCoreHabitDataGetHabitsDataGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitDataGetHabitsDataGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitDataGetHabitsDataGet$Plain(params?: ApiCoreHabitDataGetHabitsDataGet$Plain$Params, context?: HttpContext): Observable<Array<GetHabitsDataQueryResponse>> {
    return this.apiCoreHabitDataGetHabitsDataGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetHabitsDataQueryResponse>>): Array<GetHabitsDataQueryResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitDataGetHabitsDataGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitDataGetHabitsDataGet$Json$Response(params?: ApiCoreHabitDataGetHabitsDataGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetHabitsDataQueryResponse>>> {
    return apiCoreHabitDataGetHabitsDataGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitDataGetHabitsDataGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitDataGetHabitsDataGet$Json(params?: ApiCoreHabitDataGetHabitsDataGet$Json$Params, context?: HttpContext): Observable<Array<GetHabitsDataQueryResponse>> {
    return this.apiCoreHabitDataGetHabitsDataGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetHabitsDataQueryResponse>>): Array<GetHabitsDataQueryResponse> => r.body)
    );
  }

}
