/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCoreHabitAddHabitPost } from '../fn/habit/api-core-habit-add-habit-post';
import { ApiCoreHabitAddHabitPost$Params } from '../fn/habit/api-core-habit-add-habit-post';
import { apiCoreHabitEditHabitPost } from '../fn/habit/api-core-habit-edit-habit-post';
import { ApiCoreHabitEditHabitPost$Params } from '../fn/habit/api-core-habit-edit-habit-post';
import { apiCoreHabitGetHabitsGet$Json } from '../fn/habit/api-core-habit-get-habits-get-json';
import { ApiCoreHabitGetHabitsGet$Json$Params } from '../fn/habit/api-core-habit-get-habits-get-json';
import { apiCoreHabitGetHabitsGet$Plain } from '../fn/habit/api-core-habit-get-habits-get-plain';
import { ApiCoreHabitGetHabitsGet$Plain$Params } from '../fn/habit/api-core-habit-get-habits-get-plain';
import { GetHabitsListQueryResponse } from '../models/get-habits-list-query-response';

@Injectable({ providedIn: 'root' })
export class HabitService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCoreHabitAddHabitPost()` */
  static readonly ApiCoreHabitAddHabitPostPath = '/api/core/Habit/add-habit';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitAddHabitPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitAddHabitPost$Response(params: ApiCoreHabitAddHabitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCoreHabitAddHabitPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitAddHabitPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitAddHabitPost(params: ApiCoreHabitAddHabitPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCoreHabitAddHabitPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCoreHabitEditHabitPost()` */
  static readonly ApiCoreHabitEditHabitPostPath = '/api/core/Habit/edit-habit';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitEditHabitPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitEditHabitPost$Response(params: ApiCoreHabitEditHabitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCoreHabitEditHabitPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitEditHabitPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitEditHabitPost(params: ApiCoreHabitEditHabitPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCoreHabitEditHabitPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCoreHabitGetHabitsGet()` */
  static readonly ApiCoreHabitGetHabitsGetPath = '/api/core/Habit/get-habits';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitGetHabitsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitGetHabitsGet$Plain$Response(params?: ApiCoreHabitGetHabitsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetHabitsListQueryResponse>>> {
    return apiCoreHabitGetHabitsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitGetHabitsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitGetHabitsGet$Plain(params?: ApiCoreHabitGetHabitsGet$Plain$Params, context?: HttpContext): Observable<Array<GetHabitsListQueryResponse>> {
    return this.apiCoreHabitGetHabitsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetHabitsListQueryResponse>>): Array<GetHabitsListQueryResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitGetHabitsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitGetHabitsGet$Json$Response(params?: ApiCoreHabitGetHabitsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetHabitsListQueryResponse>>> {
    return apiCoreHabitGetHabitsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitGetHabitsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitGetHabitsGet$Json(params?: ApiCoreHabitGetHabitsGet$Json$Params, context?: HttpContext): Observable<Array<GetHabitsListQueryResponse>> {
    return this.apiCoreHabitGetHabitsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<GetHabitsListQueryResponse>>): Array<GetHabitsListQueryResponse> => r.body)
    );
  }

}
