/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiCoreHabitAddHabitPost } from '../fn/habit/api-core-habit-add-habit-post';
import { ApiCoreHabitAddHabitPost$Params } from '../fn/habit/api-core-habit-add-habit-post';
import { apiCoreHabitGetHabitsGet } from '../fn/habit/api-core-habit-get-habits-get';
import { ApiCoreHabitGetHabitsGet$Params } from '../fn/habit/api-core-habit-get-habits-get';

@Injectable({ providedIn: 'root' })
export class HabitService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiCoreHabitAddHabitPost()` */
  static readonly ApiCoreHabitAddHabitPostPath = '/api/core/Habit/add-habit';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitAddHabitPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitAddHabitPost$Response(params: ApiCoreHabitAddHabitPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCoreHabitAddHabitPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitAddHabitPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiCoreHabitAddHabitPost(params: ApiCoreHabitAddHabitPost$Params, context?: HttpContext): Observable<void> {
    return this.apiCoreHabitAddHabitPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiCoreHabitGetHabitsGet()` */
  static readonly ApiCoreHabitGetHabitsGetPath = '/api/core/Habit/get-habits';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiCoreHabitGetHabitsGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitGetHabitsGet$Response(params?: ApiCoreHabitGetHabitsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiCoreHabitGetHabitsGet(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiCoreHabitGetHabitsGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiCoreHabitGetHabitsGet(params?: ApiCoreHabitGetHabitsGet$Params, context?: HttpContext): Observable<void> {
    return this.apiCoreHabitGetHabitsGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
