/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetHabitsListQueryResponse } from '../../models/get-habits-list-query-response';

export interface ApiCoreHabitGetHabitsGet$Plain$Params {
}

export function apiCoreHabitGetHabitsGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCoreHabitGetHabitsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetHabitsListQueryResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiCoreHabitGetHabitsGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetHabitsListQueryResponse>>;
    })
  );
}

apiCoreHabitGetHabitsGet$Plain.PATH = '/api/core/Habit/get-habits';
