/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetHabitsDataQueryResponse } from '../../models/get-habits-data-query-response';

export interface ApiCoreHabitDataGetHabitsDataGet$Json$Params {
  date?: string;
}

export function apiCoreHabitDataGetHabitsDataGet$Json(http: HttpClient, rootUrl: string, params?: ApiCoreHabitDataGetHabitsDataGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GetHabitsDataQueryResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiCoreHabitDataGetHabitsDataGet$Json.PATH, 'get');
  if (params) {
    rb.query('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GetHabitsDataQueryResponse>>;
    })
  );
}

apiCoreHabitDataGetHabitsDataGet$Json.PATH = '/api/core/HabitData/get-habits-data';
