/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GoogleSignInCommand } from '../../models/google-sign-in-command';

export interface ApiUsermanagementAccountGoogleSignInPost$Plain$Params {
      body: GoogleSignInCommand
}

export function apiUsermanagementAccountGoogleSignInPost$Plain(http: HttpClient, rootUrl: string, params: ApiUsermanagementAccountGoogleSignInPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, apiUsermanagementAccountGoogleSignInPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

apiUsermanagementAccountGoogleSignInPost$Plain.PATH = '/api/usermanagement/Account/google-sign-in';
