version: '3.9'

services:
  bootstrapper:
    container_name: dev-bootstrapper
    build:
      context: ../Backend/
      dockerfile: Bootstrapper.Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - Npqsql__ConnectionString=${Npqsql__ConnectionString}
    ports:
      - "5002:80"
      - "5003:443"
    networks:
      - app-network-dev
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

  nginx-angular-app:
    container_name: dev-nginx-angular-app
    build:
      context: ../Frontend/frontend-spa-app
      dockerfile: Frontend.Dockerfile
      args:
        CONFIG: production
    ports:
      - "4202:80"
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      APP_NAME: ${APP_NAME}

networks:
  app-network-dev:
    driver: bridge

volumes:
  postgres_data: